<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(

    'molinos-form/admin/index'  => __DIR__ . '/view/molinos-form/admin/index.phtml',
    'molinos-form/admin/result' => __DIR__ . '/view/molinos-form/admin/result.phtml',
    'molinos-form/admin/view'   => __DIR__ . '/view/molinos-form/admin/view.phtml',
    'molinos-form/index/index'  => __DIR__ . '/view/molinos-form/index/index.phtml',
    'molinos-form/index/result' => __DIR__ . '/view/molinos-form/index/result.phtml',
);
